app:
  name: gateway
  environment: local
  url: localhost:8080   
  key: dev-key


redis:
  host: localhost
  password: ""
  port: "6379"

microservices:
  http:
    timeout: 5000
    retries: 3
    backoff_millis: 300

  movies:
    base_url: localhost:8082
    api_key: ""

  auth:
    base_url: localhost:8081
    api_key: ""

  booking:
    base_url: localhost:8083
    api_key: ""

  notification:
    base_url: localhost:8084
    api_key: ""
