app:
  name: gateway
  url: 192.168.30.100:8888

db:
  postgres:
    connection: postgres
    host: localhost
    port: 5445
    database: kinokor
    username: user
    password: 123456
    sslmode: disable

redis:
  host: redis
  password: null
  port: 6379
  cache_db: 2
  protocol: 3

microservices:
  http:
    timeout: 10
    retries: 2
    backoff_millis: 200
  booking:
    base_url: http://192.168.30.100:8881
  movies:
    base_url: http://192.168.30.100:8884
  auth:
    base_url: http://192.168.30.100:3001
  notification:
    base_url: http://192.168.30.100:8884