app:
  name: booking
  url: 127.0.0.1:8881

db:
  postgres:
    connection: postgres
    host: 192.168.30.110
    port: 5445
    database: kinokor
    username: user
    password: 123456
    sslmode: disable

redis:
  host: localhost
  password: null
  port: 6379
  cache_db: 2
  protocol: 3
