definitions:
  auth.LoginDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.RefreshTokenDTO:
    properties:
      refresh_token:
        type: string
    type: object
  password.ChangePasswordDTO:
    properties:
      new_password:
        type: string
      new_password_confirmation:
        type: string
      password:
        type: string
    type: object
  password.ForgotPasswordDTO:
    properties:
      email:
        type: string
    type: object
  password.ResetPasswordDTO:
    properties:
      email:
        type: string
      new_password:
        type: string
      new_password_confirmation:
        type: string
      token:
        type: string
    type: object
  response.CommonResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: Login
      tags:
      - Auth
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      security:
      - BearerAuth: []
      summary: Logout
      tags:
      - Auth
  /api/v1/auth/password/change:
    post:
      consumes:
      - application/json
      description: Change a password
      parameters:
      - description: Change password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/password.ChangePasswordDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      security:
      - BearerAuth: []
      summary: Change password
      tags:
      - Auth
  /api/v1/auth/password/forgot:
    post:
      consumes:
      - application/json
      description: Creating a new password
      parameters:
      - description: Forgot password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/password.ForgotPasswordDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: Forgot password
      tags:
      - Auth
  /api/v1/auth/password/reset:
    post:
      consumes:
      - application/json
      description: Reseting a password
      parameters:
      - description: Reset password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/password.ResetPasswordDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: Reset password
      tags:
      - Auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Get a refresh token
      parameters:
      - description: Refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: RefreshToken
      tags:
      - Auth
  /api/v1/cinema/{path}:
    get:
      consumes:
      - application/json
      description: Proxy all Movies API requests to movies microservice
      parameters:
      - description: Any movies path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Movies service proxy
      tags:
      - Movies
  /api/v1/film/{path}:
    delete:
      consumes:
      - application/json
      description: Proxy all Movies API requests to movies microservice
      parameters:
      - description: Any movies path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Movies service proxy
      tags:
      - Movies
    get:
      consumes:
      - application/json
      description: Proxy all Movies API requests to movies microservice
      parameters:
      - description: Any movies path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Movies service proxy
      tags:
      - Movies
    patch:
      consumes:
      - application/json
      description: Proxy all Movies API requests to movies microservice
      parameters:
      - description: Any movies path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Movies service proxy
      tags:
      - Movies
    post:
      consumes:
      - application/json
      description: Proxy all Movies API requests to movies microservice
      parameters:
      - description: Any movies path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Movies service proxy
      tags:
      - Movies
    put:
      consumes:
      - application/json
      description: Proxy all Movies API requests to movies microservice
      parameters:
      - description: Any movies path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Movies service proxy
      tags:
      - Movies
  /api/v1/genre/{path}:
    get:
      consumes:
      - application/json
      description: Proxy all Movies API requests to movies microservice
      parameters:
      - description: Any movies path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Movies service proxy
      tags:
      - Movies
  /api/v1/hall/{path}:
    get:
      consumes:
      - application/json
      description: Proxy all Movies API requests to movies microservice
      parameters:
      - description: Any movies path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Movies service proxy
      tags:
      - Movies
  /health/check:
    get:
      description: Verifies connectivity to Redis and internal services
      produces:
      - application/json
      responses: {}
      summary: Check the health status of microservices
      tags:
      - Health
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
